name: first-lab-workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ununtu-latest
    steps:
      - name: Print greeting
        run: echo "Hello world!"
      - name: Print goodbye
        run: echo "Good bye!"
